export const CHANGE_RADIUS = 'CHANGE_RADIUS';
export const CHANGE_FILTERS = 'CHANGE_FILTERS';
export const CHANGE_LOGGED_IN_USER = 'CHANGE_LOGGED_IN_USER';
export const CHANGE_PHOTOS_TO_SHOW = 'CHANGE_PHOTOS_TO_SHOW';